services:
  chatbot:
    build: .
    container_name: chatbot-app
    restart: unless-stopped
    networks:
      - chatbot-net

  nginx:
    image: nginx:alpine
    container_name: chatbot-nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - chatbot
    restart: unless-stopped
    networks:
      - chatbot-net

networks:
  chatbot-net:
    driver: bridge
