services:
  chatbot:
    build: .
    container_name: chatbot-app
    restart: unless-stopped
    networks:
      - chatbot-net

  nginx:
    image: nginx:alpine
    container_name: chatbot-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/chat-bot-globalleadersusa.duckdns.org/fullchain.pem:/etc/nginx/ssl/cert.pem:ro
      - /etc/letsencrypt/live/chat-bot-globalleadersusa.duckdns.org/privkey.pem:/etc/nginx/ssl/key.pem:ro
    depends_on:
      - chatbot
    restart: unless-stopped
    networks:
      - chatbot-net

networks:
  chatbot-net:
    driver: bridge
